# Automatically generated by configure - do not modify

all:
SRC_PATH=/home/and/Projects/qemu-wasm
TARGET_DIRS=x86_64-softmmu
GDB=
RUNC=docker
SUBDIRS= contrib/plugins
PYTHON=/home/and/Projects/qemu-wasm/build-native/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/home/and/Projects/qemu-wasm/build-native/pyvenv/bin/python3 -B /home/and/Projects/qemu-wasm/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=
MESON=/home/and/Projects/qemu-wasm/build-native/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=
TCG_TESTS_TARGETS= x86_64-softmmu
