# Automatically generated by configure - do not modify
TARGET_NAME=x86_64
TARGET=x86_64-softmmu
EXTRA_CFLAGS=-m64
CC=cc
CCAS=cc
AR=ar
AS=as
LD=ld
NM=nm
OBJCOPY=objcopy
RANLIB=ranlib
STRIP=strip
BUILD_STATIC=y
QEMU=/home/and/Projects/qemu-wasm/build-native/qemu-system-x86_64
